default[:scafandru][:user]              = 'scafandru'
default[:scafandru][:group]             = 'scafandru'
default[:scafandru][:deploy_to]         = '/srv/scafandru'
default[:scafandru][:artifact_url]      = 'http://dl.dropbox.com/u/31081437/myface-1.0.0.tar.gz'
default[:scafandru][:artifact_version]  = '1.0.0'